Repository jupyterlab/maintainer-tools, pull requests merged in 2021-12, with the labels that each got.

#19 Update PR script job name to `run`
  .github/workflows/pr_script.yml
Labels: maintenance

#21 Add downstream tester
  .github/actions/downstream-test/action.yml
  README.md
Labels: enhancement

#22 Automated Changelog Entry for 0.4.0 on main
  CHANGELOG.md
Labels: documentation

#23 Make the downstream tester more configurable
  .github/actions/downstream-test/action.yml
Labels: enhancement

#24 Automated Changelog Entry for 0.4.1 on main
  CHANGELOG.md
Labels: documentation

#26 Cache conda and improve cache prefix
  .github/actions/base-setup/action.yml
Labels: maintenance

#27 Automated Changelog Entry for 0.4.2 on main
  CHANGELOG.md
Labels: documentation

#28 Add binder link generator
  .github/actions/binder-link/action.yml
  .github/workflows/check-release.yml
  README.md
  package.json
Labels: enhancement

#29 Update body text for the Binder link comment
  .github/actions/binder-link/action.yml
Labels: maintenance

#31 Automated Changelog Entry for 0.4.3 on main
  CHANGELOG.md
Labels: documentation

#32 Fix use of `CONTENT` in `binder-link` action
  .github/actions/binder-link/action.yml
Labels: bug

#33 Automated Changelog Entry for 0.4.4 on main
  CHANGELOG.md
Labels: documentation
