Repository jupyterlab/maintainer-tools, pull requests merged in 2022-04, with the labels that each got.

#84 Fix push error
  .github/actions/update-snapshots/action.yml
Labels: bug

#83 Automatically add maintainence label for known bots
  .github/actions/enforce-label/action.yml
  README.md
Labels: enhancement

#85 Automated Changelog Entry for 0.10.0 on main
  CHANGELOG.md
Labels: documentation

#86 Upload snapshots as artifact
  .github/actions/update-snapshots/action.yml
Labels: enhancement

#87 Clean up log output and use boolean input value in pr_script workflow
  .github/actions/base-setup/action.yml
  .github/actions/downstream-test/action.yml
  .github/actions/install-minimums/action.yml
  .github/actions/test-sdist/action.yml
  .github/workflows/pr_script.yml
Labels: maintenance

#88 Fix typo
  .github/actions/enforce-label/action.yml
Labels: bug

#89 Automated Changelog Entry for 0.11.0 on main
  CHANGELOG.md
Labels: documentation

#90 Fix default test command in test-sdist
  .github/actions/test-sdist/action.yml
Labels: bug

#92 Fix bot user names
  .github/actions/enforce-label/action.yml
Labels: bug

#93 Automated Changelog Entry for 0.11.1 on main
  CHANGELOG.md
Labels: documentation

#95 Fix auto maintainence label for bots
  .github/actions/enforce-label/action.yml
Labels: bug

#96 Automated Changelog Entry for 0.11.2 on main
  CHANGELOG.md
Labels: documentation
