Repository jupyterlab/maintainer-tools, pull requests merged in 2022-11, with the labels that each got.

#143 Add dependabot
  .github/dependabot.yml
Labels: maintenance

#146 Add package download args option for downstream action
  .github/actions/downstream-test/action.yml
  .github/workflows/tests.yml
  README.md
Labels: enhancement

#148 Update upstream actions
  .github/actions/base-setup/action.yml
  .github/actions/make-sdist/action.yml
  .github/actions/pre-commit/action.yml
  .github/actions/test-sdist/action.yml
  package.json
Labels: maintenance

#150 Add ability to only create constraints file
  .github/actions/install-minimums/action.yml
  .github/actions/install-minimums/create_constraints_file.py
  .github/workflows/tests.yml
  README.md
Labels: enhancement

#151 Write env variable for min version
  .github/actions/install-minimums/action.yml
  .github/workflows/tests.yml
  README.md
Labels: maintenance

#154 Add more dependency verification
  .github/workflows/tests.yml
  pyproject.toml
Labels: maintenance

#155 Add mispell guard and fix pip cache
  .github/actions/base-setup/action.yml
Labels: bug

#156 Log link exceptions
  .github/actions/check-links/check_links.py
Labels: bug

#157 Disable warnings by default when running downstream tests
  .github/actions/downstream-test/action.yml
Labels: bug

#159 Clean up create constraints
  .github/actions/install-minimums/action.yml
  .github/actions/install-minimums/create_constraints_file.py
  .github/workflows/tests.yml
  pyproject.toml
Labels: bug

#161 Log the output when a link check fails
  .github/actions/check-links/check_links.py
Labels: bug

#162 Decode check links output on failure
  .github/actions/check-links/check_links.py
Labels: bug
