Repository jupyterlab/maintainer-tools, pull requests merged in 2022-10, with the labels that each got.

#127 Automated Changelog Entry for 0.14.0 on main
  CHANGELOG.md
Labels: documentation

#128 Clean up packaging dependency update
  .github/actions/base-setup/action.yml
  package.json
Labels: bug

#129 Install hatch with pip
  .github/actions/base-setup/action.yml
Labels: maintenance

#130 Fix hook name
  package.json
  pyproject.toml
Labels: bug

#131 Fix typo
  .github/workflows/tests.yml
  README.md
  package.json
Labels: documentation

#132 Fix ignore links syntax
  .github/actions/check-links/action.yml
Labels: bug

#134 Add pre-commit check
  .github/actions/pre-commit/action.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pyproject.toml
Labels: enhancement

#135 Install hatch with pipx
  .github/actions/base-setup/action.yml
  package.json
Labels: bug

#137 Update action.yml
  .github/actions/base-setup/action.yml
Labels: maintenance

#138 Fix handling of base setup
  .github/actions/base-setup/action.yml
  .github/workflows/tests.yml
Labels: bug

#139 Speed up ci and add branch protection
  .github/workflows/tests.yml
  package.json
Labels: maintenance

#140 Remove flake8 file
  .flake8
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance
