Repository jupyterlab/maintainer-tools, pull requests merged in 2022-08, with the labels that each got.

#110 Fix flake8 v5 compat
  .pre-commit-config.yaml
Labels: maintenance

#111 Fix update snapshots tests
  .github/workflows/tests.yml
Labels: maintenance

#114 Ensure package is installed with test files in test-sdist
  .github/actions/test-sdist/action.yml
Labels: bug

#115 Automated Changelog Entry for 0.11.4 on main
  CHANGELOG.md
Labels: documentation
