Repository jupyterlab/maintainer-tools, pull requests merged in 2022-02, with the labels that each got.

#42 Fix manual PR script running
  .github/actions/pr-script/pr_script.py
  .github/workflows/pr_script.yml
Labels: bug

#43 Automated Changelog Entry for 0.6.1 on main
  CHANGELOG.md
Labels: documentation

#44 Clean up usage docs for PR Script
  README.md
Labels: bug, documentation

#41 Add action to build and commit playwright snapshots
  .github/actions/update-snapshots/action.yml
  .github/workflows/tests.yml
  README.md
Labels: enhancement

#45 Fix server log redirection
  .github/actions/update-snapshots/action.yml
Labels: bug

#47 Automated Changelog Entry for 0.6.2 on main
  CHANGELOG.md
Labels: documentation

#49 Fix handling of github token in action workflow
  .github/workflows/pr_script.yml
Labels: bug

#50 Support starting server from Playwright config
  .github/actions/update-snapshots/action.yml
  .github/workflows/tests.yml
  README.md
Labels: enhancement

#52 Support git repository not in worflow root
  .github/actions/update-snapshots/action.yml
Labels: bug

#53 Automated Changelog Entry for 0.6.3 on main
  CHANGELOG.md
Labels: documentation
