Repository jupyterlab/maintainer-tools, pull requests merged in 2022-09, with the labels that each got.

#121 Upgraded python and node versions
  .github/actions/base-setup/action.yml
Labels: maintenance

#122 Automated Changelog Entry for 0.12.0 on main
  CHANGELOG.md
Labels: documentation

#123 Switch to using hatch version
  pyproject.toml
Labels: maintenance

#124 Add check links action
  .github/actions/check-links/action.yml
  .github/actions/check-links/check_links.py
  .github/workflows/check-release.yml
  .github/workflows/tests.yml
  README.md
Labels: enhancement

#125 Automated Changelog Entry for 0.13.0 on main
  CHANGELOG.md
Labels: documentation

#126 Install hatch globally
  .github/actions/base-setup/action.yml
  package.json
Labels: enhancement
