Repository jupyterlab/maintainer-tools, pull requests merged in 2023-01, with the labels that each got.

#173 Sync lint deps
  pyproject.toml
Labels: maintenance

#175 Don't fail if errors occurred when updating snapshots
  .github/actions/update-snapshots/action.yml
Labels: enhancement

#174 Updates default minimum node version from 16 to 18
  .github/actions/base-setup/action.yml
Labels: maintenance

#177 Add releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#178 Fix `continue-on-error` configuration
  .github/actions/update-snapshots/action.yml
Labels: bug

#179 Update command to get cache directory with yarn3
  .github/actions/base-setup/action.yml
Labels: enhancement

#180 Yarn cache dir action working for every version of yarn
  .github/actions/base-setup/action.yml
Labels: bug

#181 Add more linting
  .github/actions/check-links/check_links.py
  .github/actions/pr-script/pr_script.py
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance
