Repository jupyterlab/maintainer-tools, pull requests merged in 2024-03, with the labels that each got.

#222 Bump to Node.js 20 by default
  .github/actions/base-setup/action.yml
Labels: maintenance

#224 Fix `0.25.0` changelog
  CHANGELOG.md
  package.json
Labels: documentation

#225 Use uv for Package Constraints
  .github/actions/base-setup/action.yml
  .github/actions/base-setup/setup_constraints.sh
  .github/actions/install-minimums/action.yml
  .github/actions/install-minimums/create_constraints_file.py
  .github/workflows/tests.yml
  README.md
  pyproject.toml
Labels: enhancement
