Repository jupyterlab/maintainer-tools, pull requests merged in 2025-03, with the labels that each got.

#183 Update Snapshot Action: fix handling of the `browser` option
  .github/actions/update-snapshots/action.yml
Labels: maintenance

#250 Support extracting minimum constraints for monorepo
  .github/actions/base-setup/create_constraints_file.py
  .github/actions/base-setup/setup_constraints.sh
Labels: enhancement

#254 Encode branch name
  .github/actions/binder-link/action.yml
Labels: bug
